/* Copyright (C) 2019 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
 * and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable. */

using System.Collections.Generic;

namespace IB.Api.Client.IBKR
{
    /**
     * @class CommissionReport
     * @brief class representing the commissions generated by an execution.
     * @sa Execution
     */
    public class CommissionReport
    {
        /**
        * @brief the execution's id this commission belongs to.
        */
        public string ExecId { get; init; }

        /**
         * @brief the commissions cost.
         */
        public double Commission { get; init; }

        /**
        * @brief the reporting currency.
        */
        public string Currency { get; init; }

        /**
        * @brief the realized profit and loss
        */
        public double RealizedPnl { get; init; }

        /**
         * @brief The income return.
         */
        public double Yield { get; init; }

        /**
         * @brief date expressed in yyyymmdd format.
         */
        public int YieldRedemptionDate { get; init; }

        public CommissionReport()
        {
            Commission = 0;
            RealizedPnl = 0;
            Yield = 0;
            YieldRedemptionDate = 0;
        }

        public override bool Equals(object pOther)
        {
            bool lBRetVal;

            if (pOther is not CommissionReport lTheOther)
            {
                lBRetVal = false;
            }
            else if (this == pOther)
            {
                lBRetVal = true;
            }
            else
            {
                lBRetVal = ExecId.Equals(lTheOther.ExecId, System.StringComparison.Ordinal);
            }
            return lBRetVal;
        }

        public override int GetHashCode()
        {
            var hashCode = 662669467;
            hashCode *= -1521134295 + EqualityComparer<string>.Default.GetHashCode(ExecId);
            hashCode *= -1521134295 + Commission.GetHashCode();
            hashCode *= -1521134295 + EqualityComparer<string>.Default.GetHashCode(Currency);
            hashCode *= -1521134295 + RealizedPnl.GetHashCode();
            hashCode *= -1521134295 + Yield.GetHashCode();
            hashCode *= -1521134295 + YieldRedemptionDate.GetHashCode();
            return hashCode;
        }
    }
}
